DROP SCHEMA IF EXISTS db_farmacia;

CREATE DATABASE IF NOT EXISTS db_farmacia;

DROP TABLE IF EXISTS db_farmacia.tb_users;
CREATE TABLE IF NOT EXISTS db_farmacia.tb_users(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    email VARCHAR(45) NOT NULL,
    cpf VARCHAR(20) NOT NULL,
    address VARCHAR(45) NOT NULL,
    contact_number VARCHAR(45) NOT NULL,
    gender VARCHAR(5) NOT NULL,
    marital_status VARCHAR(45) NOT NULL,
    birth_date DATE NOT NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);