/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package farmacia.view.screens;

import farmacia.view.Sizes;
import farmacia.view.constants;
import farmacia.view.classes.Funcionario;
import farmacia.view.interfaces.IItemsPanel;
import farmacia.view.interfaces.ISellingsPanel;
import farmacia.view.libs.FarmaciaColors;
import farmacia.view.libs.TableUtils;
import farmacia.view.libs.mysql.dao.FuncionarioDAO;
import farmacia.view.libs.validators.Validators;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme Thomazini
 */
public class FuncionariosInternalFrame extends javax.swing.JInternalFrame implements ISellingsPanel, IItemsPanel {

    private Validators v = new Validators();

    /**
     * Creates new form FuncionarioRelatorio
     */
    public FuncionariosInternalFrame() {
        initComponents();
        TableUtils.addToolTip(tabelaFuncionario);
        loadTable(loadFuncionarios());
    }

    public ArrayList<Funcionario> loadFuncionarios() {
        ArrayList<Funcionario> response = funcionarioDAO.findAll();
        System.out.println("Loaded " + response.size() + " produtos");
        return response;
    }

    public void loadTable(ArrayList<Funcionario> funcionario) {
        System.out.println("filling table funcionarios with " + funcionario.size() + " items");
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionario.getModel();
        model.getDataVector().removeAllElements();

        for (Funcionario f : funcionario) {
            model.addRow(
                    new Object[]{f.getId(), f.getNome(), f.getEmail(), f.getCpf(), f.getCargo(), f.getLogin(), f.getSenha(), f.getCriadoEm(), f.isAtivo()});
        }
        System.out.println("filled table funcionarios successfully");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        buttonEditar = new javax.swing.JButton();
        panelEditar = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        sliderAtivo = new javax.swing.JSlider();
        ativoLabel = new javax.swing.JLabel();
        comboBoxCargo = new javax.swing.JComboBox<>();
        inputCpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cargoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputSenha = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        inputLogin = new javax.swing.JTextField();
        panelCadastrar = new javax.swing.JPanel();
        cadastrarButton = new javax.swing.JButton();
        inputCpfCadastro = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        inputEmailCadastro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        inputNomeCadastro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cargoLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        comboBoxCargoCadastro = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        inputLoginCadastro = new javax.swing.JTextField();
        inputSenhaCadastro = new javax.swing.JTextField();

        setMaximumSize(Sizes.INTERNAL_FRAME_SIZE);
        setMinimumSize(Sizes.INTERNAL_FRAME_SIZE);
        setPreferredSize(Sizes.INTERNAL_FRAME_SIZE);

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "E-mail", "CPF", "Cargo", "Login", "Senha", "Criado em", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionario);

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        panelEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        sliderAtivo.setMaximum(1);
        sliderAtivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sliderAtivoMouseClicked(evt);
            }
        });

        ativoLabel.setText("ativo");

        comboBoxCargo.setModel(constants.cargosModel2);

        try {
            inputCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("CPF");

        inputEmail.setMaximumSize(new java.awt.Dimension(120, 24));
        inputEmail.setMinimumSize(new java.awt.Dimension(120, 24));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });

        jLabel6.setText("E-mail");

        inputNome.setMaximumSize(new java.awt.Dimension(120, 24));
        inputNome.setMinimumSize(new java.awt.Dimension(120, 24));

        jLabel5.setText("Nome");

        cargoLabel.setText("Cargo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Editar");

        inputSenha.setMaximumSize(new java.awt.Dimension(120, 24));
        inputSenha.setMinimumSize(new java.awt.Dimension(120, 24));

        jLabel22.setText("Login e Senha");

        inputLogin.setMaximumSize(new java.awt.Dimension(120, 24));
        inputLogin.setMinimumSize(new java.awt.Dimension(120, 24));

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(inputEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addComponent(inputCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ativoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(134, 134, 134)
                        .addComponent(cargoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditarLayout.createSequentialGroup()
                        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEditarLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(81, 81, 81))
                            .addComponent(inputSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditarLayout.createSequentialGroup()
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ativoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditarLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(sliderAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, 0)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cargoLabel))
                .addGap(6, 6, 6)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(4, 4, 4)
                        .addComponent(inputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCadastrar.setMaximumSize(new java.awt.Dimension(302, 256));

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        try {
            inputCpfCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setText("CPF");

        inputEmailCadastro.setMaximumSize(new java.awt.Dimension(120, 24));
        inputEmailCadastro.setMinimumSize(new java.awt.Dimension(120, 24));
        inputEmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailCadastroActionPerformed(evt);
            }
        });

        jLabel18.setText("E-mail");

        inputNomeCadastro.setMaximumSize(new java.awt.Dimension(120, 24));
        inputNomeCadastro.setMinimumSize(new java.awt.Dimension(120, 24));

        jLabel19.setText("Nome");

        cargoLabel3.setText("Cargo");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setText("Cadastrar");

        comboBoxCargoCadastro.setModel(constants.cargosModel);

        jLabel21.setText("Login e Senha");

        inputLoginCadastro.setMaximumSize(new java.awt.Dimension(120, 24));
        inputLoginCadastro.setMinimumSize(new java.awt.Dimension(120, 24));

        inputSenhaCadastro.setMaximumSize(new java.awt.Dimension(120, 24));
        inputSenhaCadastro.setMinimumSize(new java.awt.Dimension(120, 24));

        javax.swing.GroupLayout panelCadastrarLayout = new javax.swing.GroupLayout(panelCadastrar);
        panelCadastrar.setLayout(panelCadastrarLayout);
        panelCadastrarLayout.setHorizontalGroup(
            panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 88, Short.MAX_VALUE))
                            .addComponent(inputEmailCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addComponent(cargoLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addComponent(comboBoxCargoCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addComponent(inputSenhaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)))
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputLoginCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelCadastrarLayout.setVerticalGroup(
            panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(4, 4, 4)
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargoLabel3)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxCargoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(4, 4, 4)
                        .addComponent(inputLoginCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonEditar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panelCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            Funcionario c = getFuncionarioFromFields();
            funcionarioDAO.execute(c, FuncionarioDAO.UPDATE);

            loadTable(loadFuncionarios());
            updateAtivo();
        } catch (Exception e) {
            System.out.println("funcionario relatorio err: " + e.getMessage());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        Funcionario funcionario = funcionarioDAO.findById(getSelectedFuncionarioId());
        fillFields(funcionario);
        updateAtivo();
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void sliderAtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderAtivoMouseClicked
        updateAtivo();
    }//GEN-LAST:event_sliderAtivoMouseClicked

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        try {
            Funcionario c = getFuncionarioCadastroFromFields();
            funcionarioDAO.execute(c, FuncionarioDAO.INSERT);

            loadTable(loadFuncionarios());
            updateAtivo();
        } catch (Exception e) {
            System.out.println("funcionario relatorio err: " + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void inputEmailCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailCadastroActionPerformed

    /**
     * Atualiza cor da label "ativo"
     */
    public void updateAtivo(){
        if (sliderAtivo.getValue() == 0) {
            ativoLabel.setForeground(FarmaciaColors.cancelRed);
        } else {
            ativoLabel.setForeground(FarmaciaColors.confirmGreen);
        }
    }
    
    /**
     *
     * @return id do funcionario selecionado na tabela
     */
    private int getSelectedFuncionarioId() {
        int index = tabelaFuncionario.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionario.getModel();

        int ID_funcionario_INDEX = 0;
        if (index != -1) {
            return (Integer) model.getValueAt(index, ID_funcionario_INDEX);
        } else {
            System.out.println("Nenhum item selecionado");
            return -1;
        }
    }

    private void fillFields(Funcionario f) {
        setCurrentEditingId(f.getId());
        inputNome.setText(f.getNome());
        inputEmail.setText(f.getEmail());
        inputCpf.setText(f.getCpf());
        comboBoxCargo.setSelectedIndex(f.getCargoIndex());
        inputLogin.setText(f.getLogin());
        inputSenha.setText(f.getSenha());

        int value = 0;
        if (f.isAtivo()) {
            value = 1;
        }
        sliderAtivo.setValue(value);
    }

    private Funcionario getFuncionarioFromFields() {
        boolean ativo = false;
        if (sliderAtivo.getValue() == 1) {
            ativo = true;
        }

        ArrayList<String> invalidFields = v.isValidRegisterFuncionario(
                inputNome.getText().toString(),
                inputEmail.getText().toString(),
                inputCpf.getText().toString(),
                comboBoxCargo.getSelectedItem().toString(),
                inputLogin.getText().toString(),
                inputSenha.getText().toString()
        );
        String invalidFieldsMessage = "Verifique os campos de\n";

        if (invalidFields.size() > 0) {
            for (int i = 0; i < invalidFields.size(); i++) {
                invalidFieldsMessage += "- " + invalidFields.get(i) + "\n";
            }
            JOptionPane.showMessageDialog(this, invalidFieldsMessage);
            throw new Error(invalidFieldsMessage);
        }
        return new Funcionario(
                getCurrentEditingId(),
                inputNome.getText(),
                inputEmail.getText(),
                inputCpf.getText(),
                comboBoxCargo.getSelectedItem().toString(),
                inputLogin.getText(),
                inputSenha.getText(),
                ativo
        );
    }

    private Funcionario getFuncionarioCadastroFromFields() {
        ArrayList<String> invalidFields = v.isValidRegisterFuncionario(
                inputNomeCadastro.getText().toString(),
                inputEmailCadastro.getText().toString(),
                inputCpfCadastro.getText().toString(),
                comboBoxCargoCadastro.getSelectedItem().toString(),
                inputLoginCadastro.getText().toString(),
                inputSenhaCadastro.getText().toString()
        );
        String invalidFieldsMessage = "Verifique os campos de\n";

        if (invalidFields.size() > 0) {
            for (int i = 0; i < invalidFields.size(); i++) {
                invalidFieldsMessage += "- " + invalidFields.get(i) + "\n";
            }
            JOptionPane.showMessageDialog(this, invalidFieldsMessage);
            throw new Error(invalidFieldsMessage);
        }
        return new Funcionario(
                getCurrentEditingId(),
                inputNomeCadastro.getText(),
                inputEmailCadastro.getText(),
                inputCpfCadastro.getText(),
                comboBoxCargoCadastro.getSelectedItem().toString(),
                inputLoginCadastro.getText(),
                inputSenhaCadastro.getText()
        );
    }

    private int currentEditingId = 0;

    /**
     * Define o id de funcionario que está sendo editado no momento
     *
     * @param id
     */
    private void setCurrentEditingId(int id) {
        this.currentEditingId = id;
    }

    private int getCurrentEditingId() {
        return currentEditingId;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ativoLabel;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel cargoLabel;
    private javax.swing.JLabel cargoLabel3;
    private javax.swing.JComboBox<String> comboBoxCargo;
    private javax.swing.JComboBox<String> comboBoxCargoCadastro;
    private javax.swing.JFormattedTextField inputCpf;
    private javax.swing.JFormattedTextField inputCpfCadastro;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputEmailCadastro;
    private javax.swing.JTextField inputLogin;
    private javax.swing.JTextField inputLoginCadastro;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputNomeCadastro;
    private javax.swing.JTextField inputSenha;
    private javax.swing.JTextField inputSenhaCadastro;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCadastrar;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JButton saveButton;
    private javax.swing.JSlider sliderAtivo;
    private javax.swing.JTable tabelaFuncionario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void confirmPressed(int newStep) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
        // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void cancelPressed(int newStep) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
        // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void reloadTable() {
        loadTable(loadFuncionarios());
    }
}
