/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia.view.screens;

import farmacia.view.interfaces.ILoginListener;
import java.util.ArrayList;
import farmacia.view.interfaces.ISellingsPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author kcalixto
 */
public class SellingsInternalFrame extends javax.swing.JInternalFrame implements ILoginListener, ISellingsPanel {
    
    private byte STEP = STEP_GET_CPF;
    
    private ArrayList<ILoginListener> listeners = new ArrayList<ILoginListener>();
    
    /**
     * Creates new form SellingsInternalFrame
     */
    public SellingsInternalFrame() {
        initComponents();
        startCpfTrack();
    }
    
    public void addListener(ILoginListener toAdd) {
        listeners.add(toAdd);
    }
    
    public void startCpfTrack(){
        // Listenning logout button
        getCPFPanel.addLoginListener(this);
        // Listenning buttons pressed
        getCPFPanel.addSellingsListener(this);
        showCPFPanel.addSellingsListener(this);
        registerCPFPanel.addSellingsListener(this);
        confirmCPFPanel.addSellingsListener(this);
        sellingsPanel.addSellingsListener(this);
        confirmSelling.addSellingsListener(this);
        
        //Starting screen with first Step
        this.clearPanel();
        getCPFPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        getCPFPanel = new farmacia.view.screens.sellingsPanels.GetCPFPanel();
        showCPFPanel = new farmacia.view.screens.sellingsPanels.ShowCPFPanel();
        registerCPFPanel = new farmacia.view.screens.sellingsPanels.RegisterCPFPanel();
        confirmCPFPanel = new farmacia.view.screens.sellingsPanels.ConfirmCPFPanel();
        sellingsPanel = new farmacia.view.screens.sellingsPanels.SellingsPanel();
        confirmSelling = new farmacia.view.screens.sellingsPanels.ConfirmSelling();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(getCPFPanel, "card2");
        jPanel1.add(showCPFPanel, "card3");
        jPanel1.add(registerCPFPanel, "card4");
        jPanel1.add(confirmCPFPanel, "card7");
        jPanel1.add(sellingsPanel, "card5");
        jPanel1.add(confirmSelling, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private farmacia.view.screens.sellingsPanels.ConfirmCPFPanel confirmCPFPanel;
    private farmacia.view.screens.sellingsPanels.ConfirmSelling confirmSelling;
    private farmacia.view.screens.sellingsPanels.GetCPFPanel getCPFPanel;
    private javax.swing.JPanel jPanel1;
    private farmacia.view.screens.sellingsPanels.RegisterCPFPanel registerCPFPanel;
    private farmacia.view.screens.sellingsPanels.SellingsPanel sellingsPanel;
    private farmacia.view.screens.sellingsPanels.ShowCPFPanel showCPFPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void login() {
        this.setVisible(true);
    }

    @Override
    public void logout() {
        System.out.println("called logout action");

        // Notify everybody that may be interested.
        for (ILoginListener ll : listeners) {
            ll.logout();
        }
        this.setVisible(false);
    }
    
    @Override
    public void confirmPressed(byte newStep) {
        handleSteps(newStep);
    }
    
    @Override
    public void cancelPressed(byte newStep) {
        handleSteps(newStep);
    }
    
    private void handleSteps(byte newStep){
        int YES = 0;
        int NO = 1;
        int CANCEL = 2;
        
        this.STEP = newStep;
        switch(STEP){
            case STEP_GET_CPF:
                System.out.println("step getCpf");
                clearPanel();
                getCPFPanel.setVisible(true);
                
                break;
            case STEP_SHOW_CPF:
                System.out.println("step cpfData");
                clearPanel();
                showCPFPanel.setVisible(true);
                
                break;
            case STEP_CPF_REGISTER:
                System.out.println("step registerCpf");
                clearPanel();
                registerCPFPanel.setVisible(true);
                
                break;
            case STEP_CONFIRM_CPF_DATA:
                System.out.println("step confirmCPFData");
                clearPanel();
                confirmCPFPanel.setVisible(true);
                
                break;
            case STEP_SELLINGS:
                System.out.println("step sellings");
                clearPanel();
                sellingsPanel.setVisible(true);
                
                break;
            case STEP_CONFIRM_SELLING:
                System.out.println("step confirmSelling");
                int confirm = JOptionPane.showConfirmDialog(this, "Confirmar Compra?");
                
                if(confirm == YES) {
                    clearPanel();
                    confirmSelling.setVisible(true);
                } else {
                    // Do Nothing
                }
                
                break;
            case STEP_CANCEL_SELLING:
                System.out.println("step cancelSelling");
                int cancel = JOptionPane.showConfirmDialog(this, "Cancelar Compra?");

                if(cancel == YES) {
                    clearPanel();
                    getCPFPanel.setVisible(true);
                } else {
                    // Do Nothing
                }
                
                break;
            default:
                System.out.println("unknown step: " + STEP);
                break;
        }
    }
    
    private void clearPanel(){
        getCPFPanel.setVisible(false);
        showCPFPanel.setVisible(false);
        registerCPFPanel.setVisible(false);
        confirmCPFPanel.setVisible(false);
        sellingsPanel.setVisible(false);
        confirmSelling.setVisible(false);
    }
}
