/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia.view;

import farmacia.view.items.ItemsInternalFrame;
import farmacia.view.sellings.SellingsInternalFrame;

/**
 *
 * @author kcalixto
 */
public class MainFrame extends javax.swing.JFrame {

    private SellingsInternalFrame sellingsInternalFrame = new SellingsInternalFrame();
    private ItemsInternalFrame itemsInternalFrame = new ItemsInternalFrame();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        StartSellingsFrame();
        StartItemsFrame();
    }

    public void StartSellingsFrame() {
        DesktopFrame.add(sellingsInternalFrame);
        sellingsInternalFrame.show();
        sellingsInternalFrame.setVisible(true);
    }

    public void StartItemsFrame() {
        DesktopFrame.add(itemsInternalFrame);
        itemsInternalFrame.show();
        itemsInternalFrame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopFrame = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        SellingsMenuItem = new javax.swing.JMenu();
        ItemsMenuItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 690));
        setMinimumSize(new java.awt.Dimension(650, 690));
        setPreferredSize(new java.awt.Dimension(650, 690));
        setResizable(false);

        DesktopFrame.setBackground(new java.awt.Color(255, 255, 255));
        DesktopFrame.setMaximumSize(new java.awt.Dimension(640, 640));
        DesktopFrame.setMinimumSize(new java.awt.Dimension(640, 640));
        DesktopFrame.setPreferredSize(new java.awt.Dimension(640, 640));
        DesktopFrame.setSize(new java.awt.Dimension(640, 640));

        SellingsMenuItem.setText("Tela de Vendas");
        SellingsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellingsMenuItemMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SellingsMenuItemMouseExited(evt);
            }
        });
        jMenuBar1.add(SellingsMenuItem);

        ItemsMenuItem.setText("Tela de Cadastro/Consulta de Items");
        ItemsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemsMenuItemMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItemsMenuItemMouseExited(evt);
            }
        });
        jMenuBar1.add(ItemsMenuItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SellingsMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellingsMenuItemMouseExited
        SellingsMenuItem.setSelected(false);
    }//GEN-LAST:event_SellingsMenuItemMouseExited

    private void ItemsMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsMenuItemMouseExited
        ItemsMenuItem.setSelected(false);
    }//GEN-LAST:event_ItemsMenuItemMouseExited

    private void SellingsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellingsMenuItemMouseClicked
        itemsInternalFrame.setVisible(false);
        sellingsInternalFrame.setVisible(true);
    }//GEN-LAST:event_SellingsMenuItemMouseClicked

    private void ItemsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsMenuItemMouseClicked
        itemsInternalFrame.setVisible(true);
        sellingsInternalFrame.setVisible(false);
    }//GEN-LAST:event_ItemsMenuItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopFrame;
    private javax.swing.JMenu ItemsMenuItem;
    private javax.swing.JMenu SellingsMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
