/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia.view;

import farmacia.view.screens.ItemsInternalFrame;
import farmacia.view.screens.LoginPanel;
import farmacia.view.screens.SellingsInternalFrame;
import farmacia.view.interfaces.ILoginListener;

/**
 *
 * @author kcalixto
 */
public class MainFrame extends javax.swing.JFrame implements ILoginListener {

    private LoginPanel loginPanel = new LoginPanel();

    private SellingsInternalFrame sellingsInternalFrame = new SellingsInternalFrame();
    private ItemsInternalFrame itemsInternalFrame = new ItemsInternalFrame();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        StartSellingsFrame();
        StartItemsFrame();
        LoginPanel();
    }

    @Override
    public void login() {
        LoggedInAction();
        System.out.println("recieved login action!");
    }
    @Override
    public void logout() {
        LoggedOutAction();
        System.out.println("recieved logout action!");
    }
    
    private void LoggedInAction(){
        loginPanel.setVisible(false);
        desktopFrame.setVisible(true);
        menuBar.setVisible(true);
        sellingsInternalFrame.setVisible(true);
        //set visible
    }
    
    private void LoggedOutAction(){
        loginPanel.setVisible(true);
        desktopFrame.setVisible(false);
        menuBar.setVisible(false);
    }
    
    public void StartSellingsFrame() {
        desktopFrame.add(sellingsInternalFrame);
        sellingsInternalFrame.show();
        sellingsInternalFrame.addListener(this);
        sellingsInternalFrame.setVisible(false);        
    }

    public void StartItemsFrame() {
        desktopFrame.add(itemsInternalFrame);
        itemsInternalFrame.show();
        itemsInternalFrame.setVisible(false);
    }
    
    public void LoginPanel(){
        this.add(loginPanel);
        loginPanel.setVisible(true);
        loginPanel.addListener(this);
        
        desktopFrame.setVisible(false);
        menuBar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopFrame = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        sellingsMenuItem = new javax.swing.JMenu();
        itemsMenuItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 690));
        setMinimumSize(new java.awt.Dimension(650, 690));
        setPreferredSize(new java.awt.Dimension(650, 690));
        setResizable(false);

        desktopFrame.setBackground(new java.awt.Color(255, 255, 255));
        desktopFrame.setMaximumSize(new java.awt.Dimension(640, 640));
        desktopFrame.setMinimumSize(new java.awt.Dimension(640, 640));
        desktopFrame.setPreferredSize(new java.awt.Dimension(640, 640));
        desktopFrame.setSize(new java.awt.Dimension(640, 640));

        sellingsMenuItem.setText("Tela de Vendas");
        sellingsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellingsMenuItemMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sellingsMenuItemMouseExited(evt);
            }
        });
        menuBar.add(sellingsMenuItem);

        itemsMenuItem.setText("Tela de Cadastro/Consulta de Items");
        itemsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsMenuItemMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemsMenuItemMouseExited(evt);
            }
        });
        menuBar.add(itemsMenuItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellingsMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellingsMenuItemMouseExited
        sellingsMenuItem.setSelected(false);
    }//GEN-LAST:event_sellingsMenuItemMouseExited

    private void itemsMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMenuItemMouseExited
        itemsMenuItem.setSelected(false);
    }//GEN-LAST:event_itemsMenuItemMouseExited

    private void sellingsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellingsMenuItemMouseClicked
        itemsInternalFrame.setVisible(false);
        sellingsInternalFrame.setVisible(true);
    }//GEN-LAST:event_sellingsMenuItemMouseClicked

    private void itemsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMenuItemMouseClicked
        itemsInternalFrame.setVisible(true);
        sellingsInternalFrame.setVisible(false);
    }//GEN-LAST:event_itemsMenuItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopFrame;
    private javax.swing.JMenu itemsMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu sellingsMenuItem;
    // End of variables declaration//GEN-END:variables

}
